"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .clienterror import ClientError
from typing import Any, TYPE_CHECKING

from postivo_client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .errorresponse import ErrorResponse, ErrorResponseData
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError
    from .sdkdefaulterror import SDKDefaultError

__all__ = [
    "ClientError",
    "ErrorResponse",
    "ErrorResponseData",
    "NoResponseError",
    "ResponseValidationError",
    "SDKDefaultError",
]

_dynamic_imports: dict[str, str] = {
    "ErrorResponse": ".errorresponse",
    "ErrorResponseData": ".errorresponse",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
    "SDKDefaultError": ".sdkdefaulterror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
