"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errorresponse import ErrorResponse, ErrorResponseTypedDict
from postivo_client.types import BaseModel, UNSET_SENTINEL
from postivo_client.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Dict, List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ContactHandling = Literal[
    # Detach contacts from the removed group; keep them in the Address Book.
    "detach",
    # Delete the group and also remove contacts that belong only to this group.
    "delete",
]
r"""How to handle contacts that belong to the group."""


class DeleteGroupRequestTypedDict(TypedDict):
    id: int
    r"""Group `id` to remove."""
    contacts: NotRequired[ContactHandling]
    r"""How to handle contacts that belong to the group."""


class DeleteGroupRequest(BaseModel):
    id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Group `id` to remove."""

    contacts: Annotated[
        Optional[ContactHandling],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "detach"
    r"""How to handle contacts that belong to the group."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contacts"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeleteGroupResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: NotRequired[ErrorResponseTypedDict]


class DeleteGroupResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Optional[ErrorResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
