"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from postivo_client.types import BaseModel, Nullable, OptionalNullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class DocumentPdfTypedDict(TypedDict):
    r"""PDF document payload."""

    file_stream: str
    r"""Base64-encoded PDF content."""
    file_name: NotRequired[Nullable[str]]
    r"""Optional file name for identification purposes."""


class DocumentPdf(BaseModel):
    r"""PDF document payload."""

    file_stream: str
    r"""Base64-encoded PDF content."""

    file_name: OptionalNullable[str] = None
    r"""Optional file name for identification purposes."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["file_name"])
        nullable_fields = set(["file_name"])
        null_default_fields = set(["file_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (
                    self.__pydantic_fields_set__.intersection({n})
                    or k in null_default_fields
                )  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
