"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from postivo_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ErrorResponseTypedDict(TypedDict):
    r"""Problem Details object (RFC 9457) describing the error."""

    type: NotRequired[str]
    r"""URI that identifies the problem type."""
    status: NotRequired[int]
    r"""HTTP status code generated by the origin server for this occurrence of the problem."""
    title: NotRequired[str]
    r"""Short, human-readable summary of the problem type."""
    detail: NotRequired[str]
    r"""Human-readable explanation specific to this occurrence of the problem."""
    code: NotRequired[str]
    r"""API-specific error code to help the provider team classify the error."""
    instance: NotRequired[str]
    r"""URI that identifies this specific occurrence of the problem."""


class ErrorResponse(BaseModel):
    r"""Problem Details object (RFC 9457) describing the error."""

    type: Optional[str] = None
    r"""URI that identifies the problem type."""

    status: Optional[int] = None
    r"""HTTP status code generated by the origin server for this occurrence of the problem."""

    title: Optional[str] = None
    r"""Short, human-readable summary of the problem type."""

    detail: Optional[str] = None
    r"""Human-readable explanation specific to this occurrence of the problem."""

    code: Optional[str] = None
    r"""API-specific error code to help the provider team classify the error."""

    instance: Optional[str] = None
    r"""URI that identifies this specific occurrence of the problem."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "status", "title", "detail", "code", "instance"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
