"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from postivo_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GroupResponseTypedDict(TypedDict):
    r"""Address Book group details returned by the API."""

    name: str
    r"""Group name."""
    id: int
    r"""Unique system-assigned group ID."""
    description: NotRequired[Nullable[str]]
    r"""Optional group description."""
    inherited: NotRequired[bool]
    r"""Indicates whether the group data was inherited from a main account’s shared Address Book."""


class GroupResponse(BaseModel):
    r"""Address Book group details returned by the API."""

    name: str
    r"""Group name."""

    id: int
    r"""Unique system-assigned group ID."""

    description: OptionalNullable[str] = UNSET
    r"""Optional group description."""

    inherited: Optional[bool] = None
    r"""Indicates whether the group data was inherited from a main account’s shared Address Book."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "inherited"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
