"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from postivo_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PingResponseTypedDict(TypedDict):
    r"""Ping response."""

    status: NotRequired[str]
    r"""API service status: OK (available), ERR (unavailable)."""
    version: NotRequired[str]
    r"""Current API version."""
    sandbox: NotRequired[bool]
    r"""Indicates whether the connection was established to the test system (SANDBOX)."""


class PingResponse(BaseModel):
    r"""Ping response."""

    status: Optional[str] = None
    r"""API service status: OK (available), ERR (unavailable)."""

    version: Optional[str] = None
    r"""Current API version."""

    sandbox: Optional[bool] = None
    r"""Indicates whether the connection was established to the test system (SANDBOX)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "version", "sandbox"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
