"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errorresponse import ErrorResponse, ErrorResponseTypedDict
from postivo_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ShipmentCancellationTypedDict(TypedDict):
    r"""Result of cancelling a single shipment"""

    id: NotRequired[str]
    r"""Shipment ID."""
    status: NotRequired[int]
    r"""Cancellation status code (`204` if cancelled successfully; otherwise an error code)."""
    error: NotRequired[Nullable[ErrorResponseTypedDict]]
    r"""Problem Details object (RFC 9457) describing the error."""


class ShipmentCancellation(BaseModel):
    r"""Result of cancelling a single shipment"""

    id: Optional[str] = None
    r"""Shipment ID."""

    status: Optional[int] = None
    r"""Cancellation status code (`204` if cancelled successfully; otherwise an error code)."""

    error: OptionalNullable[ErrorResponse] = UNSET
    r"""Problem Details object (RFC 9457) describing the error."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "status", "error"])
        nullable_fields = set(["error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
