"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from postivo_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StatusEventTypedDict(TypedDict):
    r"""Single shipment status event."""

    unique_id: NotRequired[int]
    r"""Unique status event ID."""
    type: NotRequired[str]
    r"""Event type: `OK` (regular) or `EX` (exception/irregular)."""
    code: NotRequired[str]
    r"""Status event code."""
    name: NotRequired[str]
    r"""Status event description."""
    details: NotRequired[Nullable[str]]
    r"""Status event details (for EXTERNAL status codes)."""
    date_: NotRequired[datetime]
    r"""Status event timestamp (UTC)."""


class StatusEvent(BaseModel):
    r"""Single shipment status event."""

    unique_id: Optional[int] = None
    r"""Unique status event ID."""

    type: Optional[str] = None
    r"""Event type: `OK` (regular) or `EX` (exception/irregular)."""

    code: Optional[str] = None
    r"""Status event code."""

    name: Optional[str] = None
    r"""Status event description."""

    details: OptionalNullable[str] = UNSET
    r"""Status event details (for EXTERNAL status codes)."""

    date_: Annotated[Optional[datetime], pydantic.Field(alias="date")] = None
    r"""Status event timestamp (UTC)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["unique_id", "type", "code", "name", "details", "date"])
        nullable_fields = set(["details"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    StatusEvent.model_rebuild()
except NameError:
    pass
