"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .errorresponse import ErrorResponse, ErrorResponseTypedDict
from postivo_client.types import BaseModel, UNSET_SENTINEL
from postivo_client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class VerifySenderRequestBodyTypedDict(TypedDict):
    r"""Verification code received in the letter."""

    verification_code: str


class VerifySenderRequestBody(BaseModel):
    r"""Verification code received in the letter."""

    verification_code: str


class VerifySenderRequestTypedDict(TypedDict):
    id: int
    r"""ID of the sender to verify."""
    request_body: VerifySenderRequestBodyTypedDict
    r"""Verification code received in the letter."""


class VerifySenderRequest(BaseModel):
    id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the sender to verify."""

    request_body: Annotated[
        VerifySenderRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Verification code received in the letter."""


class VerifySenderResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: NotRequired[ErrorResponseTypedDict]


class VerifySenderResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: Optional[ErrorResponse] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Result"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
