name: Upload Python Package (uv)

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # (opcjonalnie) upewnij się, że poetry nie miesza w środowisku
      # - name: Install Poetry (only if you actually need it)
      #   run: pip install poetry

      - name: Publish to PyPI with uv
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          chmod +x ./scripts/publish.sh
          ./scripts/publish.sh
